#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# # Retrieves the Terraform inventory for a given clusterId
# ------------------------------------------------------------------------------

source $HOME/.concord/concord.bash
[ -z ${1} ] && echo && echo "You must provide a secret id" && echo && exit
concord_secret_delete $1
