#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# # Retrieves the Terraform inventory for a given clusterId
# ------------------------------------------------------------------------------

source $HOME/.concord/concord.bash

for secret in $(concord_secrets_list)
do
  concord_secret_delete $secret
done
