#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# # Retrieves the Terraform inventory for a given clusterId
# ------------------------------------------------------------------------------

source $HOME/.concord/concord.bash
concord_show_variables
